### ISSUE TITLE
How can I install the 1.0.4 version on m5stacks c plus 2?

### ISSUE THREAD

**Issue by gitdigere** [AH2005NA/m5stick-shark#10]
I can't find the new version on M5Burner. I'm trying to install by arduino ide 2.3.3 but i don't know if I am on the good way.

**Comment by VirtualMoss7251** [comment]
there is a tuturial in readme of this project called Building from source

**Comment by VirtualMoss7251** [comment]
https://github.com/AH2005NA/m5stick-shark?tab=readme-ov-file#building-from-source

**Comment by gitdigere** [comment]
thanks man! it was easier than I expect
