### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by gitdigere** [AH2005NA/m5stick-shark#11]
c:/users/pc1/appdata/local/arduino15/packages/m5stack/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\PC1\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1/tools/sdk/esp32/lib\libnet80211.a(ieee80211_output.o): in function `ieee80211_raw_frame_sanity_check':
(.text.ieee80211_raw_frame_sanity_check+0x5c): multiple definition of `ieee80211_raw_frame_sanity_check'; sketch\m5stick-shark.ino.cpp.o:C:\Users\PC1\Desktop\m5stick-shark/deauth.h:19: first defined here
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by AH2005NA** [comment]
https://github.com/AH2005NA/m5stick-shark/tree/main/deauth_prerequisites

**Comment by gitdigere** [comment]
New error :'(
Sketch uses 2334305 bytes (111%) of program storage space. Maximum is 2097152 bytes.
Global variables use 79664 bytes (24%) of dynamic memory, leaving 248016 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board

Compilation error: text section exceeds available space in board

**Comment by FatherDivine** [comment]
> New error :'( Sketch uses 2334305 bytes (111%) of program storage space. Maximum is 2097152 bytes. Global variables use 79664 bytes (24%) of dynamic memory, leaving 248016 bytes for local variables. Maximum is 327680 bytes. Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it. text section exceeds available space in board
> 
> Compilation error: text section exceeds available space in board

You're using Arduino IDE right? It may be that you have to set the correct "Flash Size" and "Partition Scheme" in your environment. 

For instance, these are the settings for Cardputer [according to M5Stack](https://docs.m5stack.com/en/core/Cardputer) and [specifically the stampS3 chip](https://docs.m5stack.com/en/core/StampS3):

> 
> StampS3	ESP32-S3@Xtensa LX7 ,8M-FLASHWIFI,OTG\CDC Function
> Flash	8MB
> 

How I set them:
![image](https://github.com/AH2005NA/m5stick-shark/assets/150489354/aacf7239-6717-4efe-818f-4904463caca7)


You could also just export the sketch as a .bin file and upload to Cardputer using M5Launcher. To do that in Arduino IDE, press "Export > Export Compiled Library" from the top toolbar.

**Comment by gitdigere** [comment]
Solved! Thanks a lot!
