### ISSUE TITLE
New Language

### ISSUE THREAD

**Issue by PizzaPve** [AH2005NA/m5stick-shark#16]
Hello!

I translated all the menu's to dutch! You do need to import it yourself because I made them off the German language:). So you need to make the extra option for NL_NL. But anyways here it is!
[localization.txt](https://github.com/user-attachments/files/15931726/localization.txt)

Oh and if you add it pls also put me in the contributors:) thx

**Comment by AH2005NA** [comment]
I will add it if you translate this:

#elif defined(LANGUAGE_GER)
#define LOGIN_TITLE "Willkommen"
#define LOGIN_SUBTITLE "mit Google anmelden"
#define LOGIN_EMAIL_PLACEHOLDER "E-mail oder Telefonnummer"
#define LOGIN_PASSWORD_PLACEHOLDER "Passwort eingeben"
#define LOGIN_MESSAGE "Please log in to browse securely."
#define LOGIN_BUTTON "Weiter"
#define LOGIN_AFTER_MESSAGE "Daten werden geprüft..."
#define TYPE_SSID_TEXT "SSID length should be between 2 and 32\nInvalid: ?,$,\",[,\\,],+\n\nType the SSID\nPress Enter to Confirm\n\n"

**Comment by PizzaPve** [comment]
#elif defined(LANGUAGE_GER)
#define LOGIN_TITLE "Welkom"
#define LOGIN_SUBTITLE "Log in met Google"
#define LOGIN_EMAIL_PLACEHOLDER "E-mail of telefoonnummer"
#define LOGIN_PASSWORD_PLACEHOLDER "Voer wachtwoord in"
#define LOGIN_MESSAGE "Log in om veilig te browsen."
#define LOGIN_BUTTON "Verder"
#define LOGIN_AFTER_MESSAGE "Gegevens worden gecontroleerd..."
#define TYPE_SSID_TEXT "SSID length should be between 2 and 32\nInvalid: ?,$,",[,\,],+\n\nType the SSID\nPress Enter to Confirm\n\n"
