### ISSUE TITLE
IR-AH

### ISSUE THREAD

**Issue by LEGOATDU49** [AH2005NA/m5stick-shark#5]
Hi, Is the IR-AH  for controlling TVs? If so, when I use Samsung TV it doesn't do anything, maybe my TV is too old, and what does MSW mean? Is it a TV? If it can help you, I have version 1.0.3 (the latest) and the m5stickc plus 2.
Thank you in advance and have a nice day😁

**Comment by AH2005NA** [comment]
the MSW in the Samsung remote is a old command which i used to test it and i forgot to delete it, i cant say why it doesnt work with your TV... the MSW remote is for an TV that is often in scools here in Switzerland i will move this remote to the SD card when save ir remotes on sd card is fully programmed.

**Comment by LEGOATDU49** [comment]
Okay, thanks. Your firmware is very good👌
