### ISSUE TITLE
!THIS IS NOT AN ISSUE more of a question id say!

### ISSUE THREAD

**Issue by VirtualMoss7251** [AH2005NA/m5stick-shark#8]
So i am making nemo from source and i am wondering how did u make custom splash screen on boot like i know where it stored and i have been trying to figure it out tried ton of hex convertors and nothing works for me and i know that urs work cuz i tried it i have an issue where i put there my hex code and when i boot up it just gives me a black screen and than turns on the nemo UI

**Comment by AH2005NA** [comment]
https://github.com/AH2005NA/m5stick-shark/assets/112094647/de6a9a0c-4f9f-43c6-8a5f-9a0bb2426825
![WhatsApp Image 2024-05-16 at 11 21 37](https://github.com/AH2005NA/m5stick-shark/assets/112094647/6074e768-9d5f-4f0e-97dd-f9d0c92ecc1e)


if you use the nemo code then you have to change the line 
#define BITMAP M5.Lcd.drawBmp(NEMOMatrix, 97338)
to
#define BITMAP DISP.pushImage(0, 0, 240, 135, (uint16_t *)NEMOMatrix);

**Comment by VirtualMoss7251** [comment]
So i got somewhere atleast but now i have a probelam  that it shows 4 copies of the png scaled down on top of the display
EDIT: fixed it needed to change the block size in options>conversion>image to 8 bit
